apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: spring-app
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080