apiVersion: v1
kind: Namespace
metadata:
  name: level-two
  labels:
    app: level-two
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-me
  namespace: level-two
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8008
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "server { listen 8008; location / { return 200 'Hello from the other side!\nWas it easy?\n'; } }" > /etc/nginx/conf.d/default.conf &&
              nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: level-two
  labels:
    app: level-two
spec:
  type: NodePort
  selector:
    app: level-two
  ports:
    - nodePort: 30085
      port: 80
      targetPort: 80